In [28]:
import pandas as pd

In [29]:
df = pd.read_csv("intercambio-comercial-argentino-mensual.csv")

In [30]:
df

,indice_tiempo,ica_expo_totales,ica_exportacion_productos_primarios,ica_exportacion_manufacturas_origen_agropecuario,ica_exportacion_manufacturas_origen_industrial,ica_exportacion_combustible_energia,ica_importaciones_totales,ica_importaciones_bienes_capital,ica_importaciones_bienes_intermedios,ica_importaciones_combustibles_lubricantes,ica_importaciones_piezas_accesorios_bienes_capital,ica_importaciones_bienes_consumo,ica_importaciones_vehiculos_automotores_pasajeros,ica_importaciones_resto,ica_bienes_capital_partes_piezas,ica_bienes_intermedios_combustibles_lubricantes,ica_importaciones_bs_consumo_vehiculos_automotor_pasajeros,ica_saldo_comercial
0,1992-01-01,725.798174,133.367679,353.603830,169.855371,68.845548,902.946207,172.526400,361.237594,18.947876,159.296247,163.617336,26.876594,0.444160,331.822647,380.185470,190.938090,-177.148033
1,1992-02-01,851.896974,188.034116,396.893604,204.453067,62.501529,914.187817,162.811457,357.900557,17.434611,164.001829,170.042456,40.000733,1.996174,326.813286,375.335168,212.039363,-62.290843
2,1992-03-01,984.648674,320.984466,393.966223,210.621786,58.970218,1070.337821,185.928231,379.260373,19.106331,216.106944,223.549678,45.264358,1.121906,402.035175,398.366704,269.935942,-85.689147
3,1992-04-01,998.051464,375.242075,330.719966,222.833784,69.160250,1186.042169,226.014525,356.776451,35.515375,267.311883,248.000355,51.180693,1.242887,493.326408,392.291826,300.423935,-187.990705
4,1992-05-01,1137.679956,474.440656,392.913834,209.817909,60.379001,1110.860199,212.543609,344.579142,25.589576,208.210391,258.086546,60.775098,1.075837,420.754000,370.168718,319.937481,26.819757
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,2026-04-01,8915.936373,2123.447709,2708.539750,2514.383561,1569.565353,6203.139714,1141.910216,2246.801670,151.450788,1120.859892,978.293478,439.587692,124.235978,2262.770108,2398.252458,1542.117147,2712.796660
412,2026-05-01,9577.820382,2442.744387,2997.164554,2362.470720,1775.440720,6128.026460,1162.436395,2246.517906,297.444594,1034.799669,878.919091,389.457074,118.451729,2197.236065,2543.962500,1386.827895,3449.793922
413,2026-06-01,9111.849807,1894.292378,3367.476690,2416.966834,1433.113904,6876.661623,1119.194374,2343.581223,810.013591,1094.300521,922.777446,455.407167,131.387301,2213.494895,3153.594815,1509.571914,2235.188183
414,2026-07-01,8853.859533,2109.619461,3062.028030,2154.660789,1527.551253,6755.731447,1167.169110,2425.857539,630.697789,1082.767648,889.077833,448.005599,112.155928,2249.936758,3056.555328,1449.239361,2098.128087
415,2026-08-01,8882.582499,1731.252597,3301.435046,2356.245708,1493.649148,6695.991644,1310.248423,2235.134636,517.195625,1159.459951,941.430591,423.366053,109.156366,2469.708374,2752.330261,1473.953009,2186.590855

In [31]:
df.columns

Index(['indice_tiempo', 'ica_expo_totales',
       'ica_exportacion_productos_primarios',
       'ica_exportacion_manufacturas_origen_agropecuario',
       'ica_exportacion_manufacturas_origen_industrial',
       'ica_exportacion_combustible_energia', 'ica_importaciones_totales',
       'ica_importaciones_bienes_capital',
       'ica_importaciones_bienes_intermedios',
       'ica_importaciones_combustibles_lubricantes',
       'ica_importaciones_piezas_accesorios_bienes_capital',
       'ica_importaciones_bienes_consumo',
       'ica_importaciones_vehiculos_automotores_pasajeros',
       'ica_importaciones_resto', 'ica_bienes_capital_partes_piezas',
       'ica_bienes_intermedios_combustibles_lubricantes',
       'ica_importaciones_bs_consumo_vehiculos_automotor_pasajeros',
       'ica_saldo_comercial'],
      dtype='str')

In [32]:
df.shape

(416, 18)

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 416 entries, 0 to 415
Data columns (total 18 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   indice_tiempo                                               416 non-null    str
 1   ica_expo_totales                                            416 non-null    float64
 2   ica_exportacion_productos_primarios                         416 non-null    float64
 3   ica_exportacion_manufacturas_origen_agropecuario            416 non-null    float64
 4   ica_exportacion_manufacturas_origen_industrial              416 non-null    float64
 5   ica_exportacion_combustible_energia                         416 non-null    float64
 6   ica_importaciones_totales                                   416 non-null    float64
 7   ica_importaciones_bienes_capital                            416 non-null    float64
 8   ica_importaciones_bienes_intermedios                        416 non-null    float64
 9   ica_importaciones_combustibles_lubricantes                  416 non-null    float64
 10  ica_importaciones_piezas_accesorios_bienes_capital          416 non-null    float64
 11  ica_importaciones_bienes_consumo                            416 non-null    float64
 12  ica_importaciones_vehiculos_automotores_pasajeros           416 non-null    float64
 13  ica_importaciones_resto                                     416 non-null    float64
 14  ica_bienes_capital_partes_piezas                            416 non-null    float64
 15  ica_bienes_intermedios_combustibles_lubricantes             416 non-null    float64
 16  ica_importaciones_bs_consumo_vehiculos_automotor_pasajeros  416 non-null    float64
 17  ica_saldo_comercial                                         416 non-null    float64
dtypes: float64(17), str(1)
memory usage: 58.6 KB

In [34]:
df.isna().sum()

indice_tiempo                                                 0
ica_expo_totales                                              0
ica_exportacion_productos_primarios                           0
ica_exportacion_manufacturas_origen_agropecuario              0
ica_exportacion_manufacturas_origen_industrial                0
ica_exportacion_combustible_energia                           0
ica_importaciones_totales                                     0
ica_importaciones_bienes_capital                              0
ica_importaciones_bienes_intermedios                          0
ica_importaciones_combustibles_lubricantes                    0
ica_importaciones_piezas_accesorios_bienes_capital            0
ica_importaciones_bienes_consumo                              0
ica_importaciones_vehiculos_automotores_pasajeros             0
ica_importaciones_resto                                       0
ica_bienes_capital_partes_piezas                              0
ica_bienes_intermedios_combustibles_lubricantes               0
ica_importaciones_bs_consumo_vehiculos_automotor_pasajeros    0
ica_saldo_comercial                                           0
dtype: int64

In [35]:
df.dtypes

indice_tiempo                                                     str
ica_expo_totales                                              float64
ica_exportacion_productos_primarios                           float64
ica_exportacion_manufacturas_origen_agropecuario              float64
ica_exportacion_manufacturas_origen_industrial                float64
ica_exportacion_combustible_energia                           float64
ica_importaciones_totales                                     float64
ica_importaciones_bienes_capital                              float64
ica_importaciones_bienes_intermedios                          float64
ica_importaciones_combustibles_lubricantes                    float64
ica_importaciones_piezas_accesorios_bienes_capital            float64
ica_importaciones_bienes_consumo                              float64
ica_importaciones_vehiculos_automotores_pasajeros             float64
ica_importaciones_resto                                       float64
ica_bienes_capital_partes_piezas                              float64
ica_bienes_intermedios_combustibles_lubricantes               float64
ica_importaciones_bs_consumo_vehiculos_automotor_pasajeros    float64
ica_saldo_comercial                                           float64
dtype: object

In [36]:
df.duplicated().sum()

np.int64(0)

In [37]:
columnas_numericas = df.columns.drop("indice_tiempo")

for columna in columnas_numericas:
    valores = pd.to_numeric(df[columna], errors="coerce")
    invalidos = df[columna].notna() & valores.isna()

    if invalidos.any():
        print(f"\n{columna}")
        print(df.loc[invalidos, columna])

In [38]:
columnas_no_negativas = [
    "ica_expo_totales",
    "ica_exportacion_productos_primarios",
    "ica_exportacion_manufacturas_origen_agropecuario",
    "ica_exportacion_manufacturas_origen_industrial",
    "ica_exportacion_combustible_energia",
    "ica_importaciones_totales",
    "ica_importaciones_bienes_capital",
    "ica_importaciones_bienes_intermedios",
    "ica_importaciones_combustibles_lubricantes",
    "ica_importaciones_piezas_accesorios_bienes_capital",
    "ica_importaciones_bienes_consumo",
    "ica_importaciones_vehiculos_automotores_pasajeros",
    "ica_importaciones_resto"]

for columna in columnas_no_negativas:
    invalidos = df[columna] < 0

    print(f"{columna}: {invalidos.sum()} valores negativos")
    print(df.loc[invalidos, ["indice_tiempo", columna]])

ica_expo_totales: 0 valores negativos
Empty DataFrame
Columns: [indice_tiempo, ica_expo_totales]
Index: []
ica_exportacion_productos_primarios: 0 valores negativos
Empty DataFrame
Columns: [indice_tiempo, ica_exportacion_productos_primarios]
Index: []
ica_exportacion_manufacturas_origen_agropecuario: 0 valores negativos
Empty DataFrame
Columns: [indice_tiempo, ica_exportacion_manufacturas_origen_agropecuario]
Index: []
ica_exportacion_manufacturas_origen_industrial: 0 valores negativos
Empty DataFrame
Columns: [indice_tiempo, ica_exportacion_manufacturas_origen_industrial]
Index: []
ica_exportacion_combustible_energia: 0 valores negativos
Empty DataFrame
Columns: [indice_tiempo, ica_exportacion_combustible_energia]
Index: []
ica_importaciones_totales: 0 valores negativos
Empty DataFrame
Columns: [indice_tiempo, ica_importaciones_totales]
Index: []
ica_importaciones_bienes_capital: 0 valores negativos
Empty DataFrame
Columns: [indice_tiempo, ica_importaciones_bienes_capital]
Index: []
ica_importaciones_bienes_intermedios: 0 valores negativos
Empty DataFrame
Columns: [indice_tiempo, ica_importaciones_bienes_intermedios]
Index: []
ica_importaciones_combustibles_lubricantes: 0 valores negativos
Empty DataFrame
Columns: [indice_tiempo, ica_importaciones_combustibles_lubricantes]
Index: []
ica_importaciones_piezas_accesorios_bienes_capital: 0 valores negativos
Empty DataFrame
Columns: [indice_tiempo, ica_importaciones_piezas_accesorios_bienes_capital]
Index: []
ica_importaciones_bienes_consumo: 0 valores negativos
Empty DataFrame
Columns: [indice_tiempo, ica_importaciones_bienes_consumo]
Index: []
ica_importaciones_vehiculos_automotores_pasajeros: 0 valores negativos
Empty DataFrame
Columns: [indice_tiempo, ica_importaciones_vehiculos_automotores_pasajeros]
Index: []
ica_importaciones_resto: 0 valores negativos
Empty DataFrame
Columns: [indice_tiempo, ica_importaciones_resto]
Index: []

In [39]:
df['indice_tiempo'] = pd.to_datetime(df['indice_tiempo'])

In [40]:
df['indice_tiempo'].min()

Timestamp('1992-01-01 00:00:00')

In [41]:
df['indice_tiempo'].max()

Timestamp('2026-08-01 00:00:00')

In [42]:
df['indice_tiempo'].diff().value_counts()

indice_tiempo
31 days    242
30 days    138
28 days     26
29 days      9
Name: count, dtype: int64

In [43]:
df = df[ (df['indice_tiempo'] >= "2016-01-01") & (df['indice_tiempo'] <= "2026-12-01")]

In [44]:
df

,indice_tiempo,ica_expo_totales,ica_exportacion_productos_primarios,ica_exportacion_manufacturas_origen_agropecuario,ica_exportacion_manufacturas_origen_industrial,ica_exportacion_combustible_energia,ica_importaciones_totales,ica_importaciones_bienes_capital,ica_importaciones_bienes_intermedios,ica_importaciones_combustibles_lubricantes,ica_importaciones_piezas_accesorios_bienes_capital,ica_importaciones_bienes_consumo,ica_importaciones_vehiculos_automotores_pasajeros,ica_importaciones_resto,ica_bienes_capital_partes_piezas,ica_bienes_intermedios_combustibles_lubricantes,ica_importaciones_bs_consumo_vehiculos_automotor_pasajeros,ica_saldo_comercial
288,2016-01-01,3875.000000,915.000000,1830.523016,977.944014,151.000000,4124.000000,850.000000,1282.000000,294.000000,843.000000,532.000000,307.000000,15.000000,1693.000000,1576.000000,854.000000,-249.000000
289,2016-02-01,4143.000000,1104.000000,1730.000881,1174.183491,135.000000,4097.000000,850.000000,1217.000000,287.000000,925.000000,507.000000,297.000000,14.000000,1775.000000,1504.000000,818.000000,46.000000
290,2016-03-01,4426.000000,1294.000000,1753.966426,1237.579145,141.000000,4556.000000,858.000000,1368.000000,268.000000,1098.000000,622.000000,327.000000,15.000000,1956.000000,1636.000000,964.000000,-130.000000
291,2016-04-01,4743.000000,1343.000000,1835.062851,1378.867351,186.000000,4423.000000,884.000000,1312.000000,255.000000,1006.000000,569.000000,379.000000,18.000000,1890.000000,1567.000000,966.000000,320.000000
292,2016-05-01,5377.000000,1670.000000,2216.210174,1349.351059,142.000000,4874.000000,1063.000000,1429.000000,426.000000,946.000000,604.000000,389.000000,18.000000,2009.000000,1855.000000,1011.000000,503.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,2026-04-01,8915.936373,2123.447709,2708.539750,2514.383561,1569.565353,6203.139714,1141.910216,2246.801670,151.450788,1120.859892,978.293478,439.587692,124.235978,2262.770108,2398.252458,1542.117147,2712.796660
412,2026-05-01,9577.820382,2442.744387,2997.164554,2362.470720,1775.440720,6128.026460,1162.436395,2246.517906,297.444594,1034.799669,878.919091,389.457074,118.451729,2197.236065,2543.962500,1386.827895,3449.793922
413,2026-06-01,9111.849807,1894.292378,3367.476690,2416.966834,1433.113904,6876.661623,1119.194374,2343.581223,810.013591,1094.300521,922.777446,455.407167,131.387301,2213.494895,3153.594815,1509.571914,2235.188183
414,2026-07-01,8853.859533,2109.619461,3062.028030,2154.660789,1527.551253,6755.731447,1167.169110,2425.857539,630.697789,1082.767648,889.077833,448.005599,112.155928,2249.936758,3056.555328,1449.239361,2098.128087
415,2026-08-01,8882.582499,1731.252597,3301.435046,2356.245708,1493.649148,6695.991644,1310.248423,2235.134636,517.195625,1159.459951,941.430591,423.366053,109.156366,2469.708374,2752.330261,1473.953009,2186.590855

In [45]:
df['indice_tiempo'].min()

Timestamp('2016-01-01 00:00:00')

In [46]:
df['indice_tiempo'].max()

Timestamp('2026-08-01 00:00:00')

In [47]:
df = df.drop(columns=['ica_bienes_capital_partes_piezas',
             'ica_bienes_intermedios_combustibles_lubricantes',
             'ica_importaciones_combustibles_lubricantes',
             'ica_importaciones_piezas_accesorios_bienes_capital',
             'ica_importaciones_vehiculos_automotores_pasajeros',
             'ica_importaciones_resto',
             'ica_importaciones_bs_consumo_vehiculos_automotor_pasajeros'])

In [48]:
df

,indice_tiempo,ica_expo_totales,ica_exportacion_productos_primarios,ica_exportacion_manufacturas_origen_agropecuario,ica_exportacion_manufacturas_origen_industrial,ica_exportacion_combustible_energia,ica_importaciones_totales,ica_importaciones_bienes_capital,ica_importaciones_bienes_intermedios,ica_importaciones_bienes_consumo,ica_saldo_comercial
288,2016-01-01,3875.000000,915.000000,1830.523016,977.944014,151.000000,4124.000000,850.000000,1282.000000,532.000000,-249.000000
289,2016-02-01,4143.000000,1104.000000,1730.000881,1174.183491,135.000000,4097.000000,850.000000,1217.000000,507.000000,46.000000
290,2016-03-01,4426.000000,1294.000000,1753.966426,1237.579145,141.000000,4556.000000,858.000000,1368.000000,622.000000,-130.000000
291,2016-04-01,4743.000000,1343.000000,1835.062851,1378.867351,186.000000,4423.000000,884.000000,1312.000000,569.000000,320.000000
292,2016-05-01,5377.000000,1670.000000,2216.210174,1349.351059,142.000000,4874.000000,1063.000000,1429.000000,604.000000,503.000000
...,...,...,...,...,...,...,...,...,...,...,...
411,2026-04-01,8915.936373,2123.447709,2708.539750,2514.383561,1569.565353,6203.139714,1141.910216,2246.801670,978.293478,2712.796660
412,2026-05-01,9577.820382,2442.744387,2997.164554,2362.470720,1775.440720,6128.026460,1162.436395,2246.517906,878.919091,3449.793922
413,2026-06-01,9111.849807,1894.292378,3367.476690,2416.966834,1433.113904,6876.661623,1119.194374,2343.581223,922.777446,2235.188183
414,2026-07-01,8853.859533,2109.619461,3062.028030,2154.660789,1527.551253,6755.731447,1167.169110,2425.857539,889.077833,2098.128087
415,2026-08-01,8882.582499,1731.252597,3301.435046,2356.245708,1493.649148,6695.991644,1310.248423,2235.134636,941.430591,2186.590855

In [49]:

# Seleccionar todas las columnas numéricas
columnas_numericas = df.select_dtypes(include="number").columns

# Recorrer cada columna numérica
for columna in columnas_numericas:
    serie = df[columna]
    
    # Calcular cuartiles e IQR
    Q1 = serie.quantile(0.25)
    Q3 = serie.quantile(0.75)
    IQR = Q3 - Q1

    # Calcular límites
    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR

    # Identificar valores atípicos
    atipicos = df[
        (df[columna] < limite_inferior) |
        (df[columna] > limite_superior)
    ]

    # Mostrar resultados
    print(f"\nColumna: {columna}")
    print(f"Cantidad de valores atípicos: {len(atipicos)}")
    print(atipicos[["indice_tiempo", columna]])

Columna: ica_expo_totales
Cantidad de valores atípicos: 0
Empty DataFrame
Columns: [indice_tiempo, ica_expo_totales]
Index: []

Columna: ica_exportacion_productos_primarios
Cantidad de valores atípicos: 0
Empty DataFrame
Columns: [indice_tiempo, ica_exportacion_productos_primarios]
Index: []

Columna: ica_exportacion_manufacturas_origen_agropecuario
Cantidad de valores atípicos: 1
    indice_tiempo  ica_exportacion_manufacturas_origen_agropecuario
364    2022-05-01                                            3646.0

Columna: ica_exportacion_manufacturas_origen_industrial
Cantidad de valores atípicos: 1
    indice_tiempo  ica_exportacion_manufacturas_origen_industrial
339    2020-04-01                                           704.0

Columna: ica_exportacion_combustible_energia
Cantidad de valores atípicos: 4
    indice_tiempo  ica_exportacion_combustible_energia
411    2026-04-01                          1569.565353
412    2026-05-01                          1775.440720
414    2026-07-01                          1527.551253
415    2026-08-01                          1493.649148

Columna: ica_importaciones_totales
Cantidad de valores atípicos: 0
Empty DataFrame
Columns: [indice_tiempo, ica_importaciones_totales]
Index: []

Columna: ica_importaciones_bienes_capital
Cantidad de valores atípicos: 0
Empty DataFrame
Columns: [indice_tiempo, ica_importaciones_bienes_capital]
Index: []

Columna: ica_importaciones_bienes_intermedios
Cantidad de valores atípicos: 0
Empty DataFrame
Columns: [indice_tiempo, ica_importaciones_bienes_intermedios]
Index: []

Columna: ica_importaciones_bienes_consumo
Cantidad de valores atípicos: 2
    indice_tiempo  ica_importaciones_bienes_consumo
404    2025-09-01                       1157.254933
405    2025-10-01                       1194.089257

Columna: ica_saldo_comercial
Cantidad de valores atípicos: 0
Empty DataFrame
Columns: [indice_tiempo, ica_saldo_comercial]
Index: []

In [50]:
df = df.rename(columns={'indice_tiempo':'fecha'})

In [51]:
df.head(5)

,fecha,ica_expo_totales,ica_exportacion_productos_primarios,ica_exportacion_manufacturas_origen_agropecuario,ica_exportacion_manufacturas_origen_industrial,ica_exportacion_combustible_energia,ica_importaciones_totales,ica_importaciones_bienes_capital,ica_importaciones_bienes_intermedios,ica_importaciones_bienes_consumo,ica_saldo_comercial
288,2016-01-01,3875.0,915.0,1830.523016,977.944014,151.0,4124.0,850.0,1282.0,532.0,-249.0
289,2016-02-01,4143.0,1104.0,1730.000881,1174.183491,135.0,4097.0,850.0,1217.0,507.0,46.0
290,2016-03-01,4426.0,1294.0,1753.966426,1237.579145,141.0,4556.0,858.0,1368.0,622.0,-130.0
291,2016-04-01,4743.0,1343.0,1835.062851,1378.867351,186.0,4423.0,884.0,1312.0,569.0,320.0
292,2016-05-01,5377.0,1670.0,2216.210174,1349.351059,142.0,4874.0,1063.0,1429.0,604.0,503.0

In [52]:
df.to_csv("ica_limpio.csv", index=False)